services:
  agent:
    # image: microros/micro-ros-agent:humble
    build:
      dockerfile: Dockerfile.agent
    network_mode: host
    # ipc: host
    # ports:
    #   - 8888:8888/udp
    environment:
      XRCE_DOMAIN_ID_OVERRIDE: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    command: udp4 --port 8888

  listener:
    build:
      dockerfile: Dockerfile.chatter
    network_mode: host
    # ipc: host
    environment:
      ROS_DOMAIN_ID: 0
    command: ros2 run demo_nodes_cpp listener

  heartbeat:
    build:
      dockerfile: Dockerfile.chatter
    network_mode: host
    # ipc: host
    environment:
      ROS_DOMAIN_ID: 0
    command: ros2 run demo_nodes_cpp talker --ros-args -r chatter:=chatter2