services:
  agent:
    image: microros/micro-ros-agent:jazzy
    ports:
      - 8888:8888/udp
    environment:
      XRCE_DOMAIN_ID_OVERRIDE: 32
    command: udp4 --port 8888

  listener:
    build:
      dockerfile: Dockerfile.chatter
    environment:
      ROS_DOMAIN_ID: 32
    command: ros2 run demo_nodes_cpp listener

  heartbeat:
    build:
      dockerfile: Dockerfile.chatter
    environment:
      ROS_DOMAIN_ID: 32
    command: ros2 run demo_nodes_cpp talker --ros-args -r chatter:=chatter2