services:
  agent:
    image: microros/micro-ros-agent:jazzy
    ports:
      - 8888:8888/udp
    command: udp4 --port 8888

  listener:
    build:
      dockerfile: Dockerfile.chatter
    # A default 'listener' uses RMW_QOS_POLICY_RELIABILITY_RELIABLE and
    # our micro-ROS node provides data with RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT.
    # This is why need to use 'listener_best_effor' .
    # To find info about QOS setting of all subscribers and publishers to a specific topic use:
    # ros2 topic info /chatter -v
    command: ros2 run demo_nodes_cpp listener_best_effort 
